-- TRIATOMINEOS
INSERT INTO opcoes (tipo, chave, valor) VALUES
('TRIATOMINEOS', 'CONDICAO', 'VIVO'),
('TRIATOMINEOS', 'CONDICAO', 'MORTO'),
('TRIATOMINEOS', 'INSETIFUGO', 'SIM'),
('TRIATOMINEOS', 'INSETIFUGO', 'NÃO'),
('TRIATOMINEOS', 'INTRADOMICILIO', 'SIM'),
('TRIATOMINEOS', 'INTRADOMICILIO', 'NAO'),
('TRIATOMINEOS', 'PERIDOMICILIO', 'SIM'),
('TRIATOMINEOS', 'PERIDOMICILIO', 'NAO'),
('TRIATOMINEOS', 'VESTIGIOS', 'OVOS'),
('TRIATOMINEOS', 'VESTIGIOS', 'PELES'),
('TRIATOMINEOS', 'VESTIGIOS', 'FEZES');

-- MOLUSCO
INSERT INTO opcoes (tipo, chave, valor) VALUES
('MOLUSCO', 'TIPO_MOLUSCO', 'STRAMINEA'),
('MOLUSCO', 'TIPO_MOLUSCO', 'GLABRATA'),
('MOLUSCO', 'TIPO_MOLUSCO', 'OUTROS');

-- LARVA
INSERT INTO opcoes (tipo, chave, valor) VALUES
('LARVA', 'TIPO_LARVA', 'A_EGYPYTI'),
('LARVA', 'TIPO_LARVA', 'A_LBOPICTUS'),
('LARVA', 'TIPO_LARVA', 'OUTROS');

-- FLEBOTOMINEOS
INSERT INTO opcoes (tipo, chave, valor) VALUES
('FLEBOTOMINEOS', 'CLASSIFICACAO_AREA_LT', 'SURTO'),
('FLEBOTOMINEOS', 'CLASSIFICACAO_AREA_LT', 'RECENTE'),
('FLEBOTOMINEOS', 'CLASSIFICACAO_AREA_LT', 'RECORRENTE'),
('FLEBOTOMINEOS', 'CLASSIFICACAO_AREA_LV', 'VULNERAVELNRECEPTIVO'),
('FLEBOTOMINEOS', 'CLASSIFICACAO_AREA_LV', 'VULNERAVELRECEPTIVO'),
('FLEBOTOMINEOS', 'CLASSIFICACAO_AREA_LV', 'CASOSCANINOS'),
('FLEBOTOMINEOS', 'CLASSIFICACAO_AREA_LV', 'PRIMEIROCASOLV'),
('FLEBOTOMINEOS', 'CLASSIFICACAO_AREA_LV', 'SURTO'),
('FLEBOTOMINEOS', 'CLASSIFICACAO_AREA_LV', 'TBAIXAMEDIA'),
('FLEBOTOMINEOS', 'CLASSIFICACAO_AREA_LV', 'TALTA'),
('FLEBOTOMINEOS', 'ESTACAO', 'PRIMAVERA'),
('FLEBOTOMINEOS', 'ESTACAO', 'VERAO'),
('FLEBOTOMINEOS', 'ESTACAO', 'OUTONO'),
('FLEBOTOMINEOS', 'ESTACAO', 'INVERNO'),
('FLEBOTOMINEOS', 'FASES_LUA', 'CRESCENTE'),
('FLEBOTOMINEOS', 'FASES_LUA', 'CHEIA'),
('FLEBOTOMINEOS', 'FASES_LUA', 'NOVA'),
('FLEBOTOMINEOS', 'FASES_LUA', 'MINGUANTE'),
('FLEBOTOMINEOS', 'GALINHEIRO', 'SIM'),
('FLEBOTOMINEOS', 'GALINHEIRO', 'NAO'),
('FLEBOTOMINEOS', 'GALINHEIRO', 'NAOSEAPLICA'),
('FLEBOTOMINEOS', 'MATERIA_ORGANICA', 'SIM'),
('FLEBOTOMINEOS', 'MATERIA_ORGANICA', 'NAO'),
('FLEBOTOMINEOS', 'MATERIA_ORGANICA', 'NAOSEAPLICA'),
('FLEBOTOMINEOS', 'PRECIPITACAO', 'SIM'),
('FLEBOTOMINEOS', 'PRECIPITACAO', 'NAO'),
('FLEBOTOMINEOS', 'PRECIPITACAO', 'NAOSEAPLICA'),
('FLEBOTOMINEOS', 'PRESENCA_ANIMAL_INTRA', 'CAES'),
('FLEBOTOMINEOS', 'PRESENCA_ANIMAL_INTRA', 'AVES'),
('FLEBOTOMINEOS', 'PRESENCA_ANIMAL_INTRA', 'SUINOS'),
('FLEBOTOMINEOS', 'PRESENCA_ANIMAL_INTRA', 'NAOSEAPLICA'),
('FLEBOTOMINEOS', 'PRESENCA_ANIMAL_PERI', 'CAES'),
('FLEBOTOMINEOS', 'PRESENCA_ANIMAL_PERI', 'AVES'),
('FLEBOTOMINEOS', 'PRESENCA_ANIMAL_PERI', 'SUINOS'),
('FLEBOTOMINEOS', 'PRESENCA_ANIMAL_PERI', 'NAOSEAPLICA'),
('FLEBOTOMINEOS', 'TIPO_ATIVIDADE_LT', 'FOCO'),
('FLEBOTOMINEOS', 'TIPO_ATIVIDADE_LT', 'ENTOMOLOGICO'),
('FLEBOTOMINEOS', 'TIPO_ATIVIDADE_LV', 'INVESTIGACAO'),
('FLEBOTOMINEOS', 'TIPO_ATIVIDADE_LV', 'LEVANTAMENTO'),
('FLEBOTOMINEOS', 'TIPO_ATIVIDADE_LV', 'MONITORAMENTO'),
('FLEBOTOMINEOS', 'TIPO_VEGETACAO', 'FLORESTA'),
('FLEBOTOMINEOS', 'TIPO_VEGETACAO', 'SAVANA'),
('FLEBOTOMINEOS', 'TIPO_VEGETACAO', 'PRADARIA'),
('FLEBOTOMINEOS', 'TIPO_VEGETACAO', 'COMPLEXA'),
('FLEBOTOMINEOS', 'VENTO', 'PARADO'),
('FLEBOTOMINEOS', 'VENTO', 'FRACO'),
('FLEBOTOMINEOS', 'VENTO', 'MEDIO'),
('FLEBOTOMINEOS', 'VENTO', 'FORTE'),
('FLEBOTOMINEOS', 'VENTO', 'ANEMOMETRO');

-- AMOSTRA
INSERT INTO opcoes (tipo, chave, valor) VALUES
('AMOSTRA', 'EDITAR_AMOSTRA', 'ADICIONAR'),
('AMOSTRA', 'EDITAR_AMOSTRA', 'REMOVER'),
('AMOSTRA', 'RESULTADO', 'POSITIVO'),
('AMOSTRA', 'RESULTADO', 'NEGATIVO'),
('AMOSTRA', 'STATUS_AMOSTRA', 'PENDENTE'),
('AMOSTRA', 'STATUS_AMOSTRA', 'ANALISADA'),
('AMOSTRA', 'STATUS_AMOSTRA', 'DESCARTADA'),
('AMOSTRA', 'TIPO_AMOSTRA', 'ESCORPIAO'),
('AMOSTRA', 'TIPO_AMOSTRA', 'FLEBOTOMINEOS'),
('AMOSTRA', 'TIPO_AMOSTRA', 'TRIATOMINEOS'),
('AMOSTRA', 'TIPO_AMOSTRA', 'MOLUSCO'),
('AMOSTRA', 'TIPO_AMOSTRA', 'LARVAS');

-- LOTE
INSERT INTO opcoes (tipo, chave, valor) VALUES
('LOTE', 'STATUS_LOTE', 'PENDENTE'),
('LOTE', 'STATUS_LOTE', 'ENVIADO'),
('LOTE', 'STATUS_LOTE', 'DESCARTADO');